library(tidyr)
library(gridExtra)

source('utils-compare.R')
source('utils-misc.R')

dir.results    <- dir.def('dir-def.csv')[['results']]
dir.save.rdata <- dir.def('dir-def.csv')[['rdata']]


# ==== Load saved data ====

print('Loading saved RData...')
load(paste0(dir.save.rdata,'result-scen-all.RData'))
res.all <- list(main = result.scen.all,
                main.ageGroup = result.scen.all.ageGroup)
print('Saved RData loaded.')

# ----- Analyze results ----

# TO DO: CHANGE THAT MANUAL DEFINITION AND READ FROM A FILE GENERATED BY THE SCENARIO BUILDER!
col.prm <-  c("contactAssort_lambda", "frailty_sd",
              "imm_cell_max","contact_rate_CV",
              "proba_move", "asymptom_infectiousness_ratio")


file.scen.prm.list <- 'scenario-prm-list-sensana.csv'
dir <- dir.results
df  <- res.all[['main']]

bb <- process.outputs.TEST(df,dir,file.scen.prm.list)

a <- bb[[2]][['sympt']]


# Calculate the difference with baseline parameter values:
as <- a[order(a$key, -a$baseline),]
as$mn.minus.baseline <- NA
i.base <- 1
for(i in 2:nrow(as)){
    if(as$baseline[i] & (as$key[i]!=as$key[i-1]) ) i.base <- i
    as$mn.minus.baseline[i] <- as$mn[i] - as$mn[i.base]
}

# identify the bumped parameter:
baseline.prm <- as[1,col.prm]
as$bumped <- NA

for(i in 1:nrow(as)){
    idx <- which(as[i,col.prm] != baseline.prm)
    if(length(idx)==1) as$bumped[i] <- names(baseline.prm)[idx]
}

g <- ggplot(as) + 
    geom_point(aes(x=(interv_start), y=mn.minus.baseline, color=factor(interv_cvg_rate)),
               size=3, alpha=0.6) +
    facet_grid(bumped ~ interv_efficacy ) + 
    geom_hline(yintercept=0, color='darkgrey', linetype=2)
plot(g)
